env:
  es6: true
  node: true
  jest: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 2017
  sourceType: module
rules:
  indent:
  - error
  - 4
  quotes:
  - error
  - single
  semi:
  - error
  - always
  no-console:
  - off
